### ISSUE TITLE
As admin I can add new content  [dla juniora]

### ISSUE THREAD

**Issue by BartlomiejBartnicki** [karunaproject/be#3]
Task can be start after https://github.com/karunaproject/be/issues/1 is closed.

Definition on Done
1. create endpoint POST addOrUpdateContent(page: string nullable, key: string, value: string) 
2. Only admins can use this endpoint (with JWT that mach to any admin)
3. if authorization fail return 401 error
4. if row with same page and key exists update it
5. write unit test/tests
6. merge branch to master after review

Celem tego zadania jest umożliwienie dodawania i aktualizowania pojedeyńczych contentów.
Tylko administratorzy mają do tego prawo.

**Comment by misterrevo** [comment]
MassContentWrapper massUpdateContent(@RequestBody MassContentWrapperRequest massContentWrapperRequest) {
        return contentService.massUpdateContent(massContentWrapperRequest);
    }

    MassContentWrapper massAddContent(@RequestBody MassContentWrapperRequest massContentWrapperRequest) {
        return contentService.massAddContent(massContentWrapperRequest);
    }

this methods, don't do this logic? @KrystynaCal @BarSwi

**Comment by KrystynaCal** [comment]
endpoint  addOrUpdateContent is deprecated. The logic has been changed to massAddContent
