### ISSUE TITLE
As Visitor I can send message  [dla juniora]

### ISSUE THREAD

**Issue by BartlomiejBartnicki** [karunaproject/be#7]
Definition on Done

1. create table visitors_message(create_at: date auto, body max(1024): String, contact: String max(256))
 - can return {error: BODY_TO_LONG} or {error: CONTACT_TO_LONG}
3. create endpoint POST sendMessage(body, contact)
4. write unit test/tests
5. merge branch to master after review
Celem zadania jest stworzenie endpointu dla formularza kontaktowego na stronie. Walidacja poprawności kontaktu będzie po stronie FE (jeszcze nie wiemy czy będzie to email, czy numer telefonu lub dowolna z tych dwóch wartości). Aby się zabezpieczyć przed zapchaniem bazy danych ogarniczamy długość body i contact.
Wywołanie endpointu powoduje zapisanie w bazie wiadomości. Wysłanie maila NIE jest w zakresie tego zadania

**Comment by misterrevo** [comment]
@karunaproject/devs somebody take this task? i see it in todo not blocked so im confused, because no body is assigne, if no body take it i can do it 🗡
